name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: python3 build.py

      - name: Upload x86_64 binary
        uses: actions/upload-artifact@v4
        with:
          name: laptop_exporter-x86_64
          path: target/x86_64-unknown-linux-gnu/release/laptop_exporter

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: laptop_exporter-aarch64
          path: target/aarch64-unknown-linux-gnu/release/laptop_exporter

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/laptop_exporter
            target/aarch64-unknown-linux-gnu/release/laptop_exporter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
