name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Build
        run: python3 build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          body: |
            Tain CLI v0.6.1
            - Built for `aarch64-unknown-linux-gnu`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
